export const ADD_MOVIE = "ADD_MOVIE";
export const TOGGLE_ISLOADING = "TOGGLE_ISLOADING";
export const SET_ISERROR_TRUE = "SET_ISERROR_TRUE";
export const SET_ISERROR_FALSE = "SET_ISERROR_FALSE";

export const SHOW_FILMBODY = "SHOW_FILMBODY";
export const CLOSE_FILMBODY = "CLOSE_FILMBODY";

export const SET_NUMBER_OF_FILMS = "SET_NUMBER_OF_FILMS";

export const TOGGLE_SUCCESS_POST_MODAL = "TOGGLE_SUCCESS_POST_MODAL";
export const TOGGLE_POST_ISERROR = "TOGGLE_POST_ISERROR";
export const POST_ISLOADING_TRUE = "POST_ISLOADING_TRUE";
export const POST_ISLOADING_FALSE = "POST_ISLOADING_FALSE";

export const TOGGLE_SUCCESS_DELETE_MODAL = "TOGGLE_SUCCESS_DELETE_MODAL";
export const TOGGLE_DELETE_ISERROR = "TOGGLE_DELETE_ISERROR";
export const DELETE_ISLOADING_TRUE = "DELETE_ISLOADING_TRUE";
export const DELETE_ISLOADING_FALSE = "DELETE_ISLOADING_FALSE";

export const TOGGLE_SUCCESS_EDIT_MODAL = "TOGGLE_SUCCESS_EDIT_MODAL";
export const EDIT_ISLOADING_TRUE = "EDIT_ISLOADING_TRUE";
export const EDIT_ISLOADING_FALSE = "EDIT_ISLOADING_FALSE";
export const TOGGLE_EDIT_ISERROR = "TOGGLE_EDIT_ISERROR";