export const ADD_MOVIE = "ADD_MOVIE";
export const TOGGLE_ISLOADING = "TOGGLE_ISLOADING";
export const SET_ISERROR_TRUE = "SET_ISERROR_TRUE";
export const SET_ISERROR_FALSE = "SET_ISERROR_FALSE";
export const SHOW_FILMBODY = "SHOW_FILMBODY";
export const CLOSE_FILMBODY = "CLOSE_FILMBODY";
export const SET_NUMBER_OF_FILMS = "SET_NUMBER_OF_FILMS";